// Copyright Example 2021

// Leading Comment
// leading comment block

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.14.0
// source: tests/proto/asset.proto

package test

import (
	proto "github.com/golang/protobuf/proto"
	_ "github.com/intrinsec/protoc-gen-sanitize/sanitize"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Asset1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value int64  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	Text  string `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	Uuid  string `protobuf:"bytes,4,opt,name=uuid,proto3" json:"uuid,omitempty"`
}

func (x *Asset1) Reset() {
	*x = Asset1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tests_proto_asset_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Asset1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Asset1) ProtoMessage() {}

func (x *Asset1) ProtoReflect() protoreflect.Message {
	mi := &file_tests_proto_asset_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Asset1.ProtoReflect.Descriptor instead.
func (*Asset1) Descriptor() ([]byte, []int) {
	return file_tests_proto_asset_proto_rawDescGZIP(), []int{0}
}

func (x *Asset1) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Asset1) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Asset1) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Asset1) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type Asset2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value int64  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	Uuid  string `protobuf:"bytes,3,opt,name=uuid,proto3" json:"uuid,omitempty"`
}

func (x *Asset2) Reset() {
	*x = Asset2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tests_proto_asset_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Asset2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Asset2) ProtoMessage() {}

func (x *Asset2) ProtoReflect() protoreflect.Message {
	mi := &file_tests_proto_asset_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Asset2.ProtoReflect.Descriptor instead.
func (*Asset2) Descriptor() ([]byte, []int) {
	return file_tests_proto_asset_proto_rawDescGZIP(), []int{1}
}

func (x *Asset2) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Asset2) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Asset2) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type Asset3 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value int64  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	Text  string `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	Uuid  string `protobuf:"bytes,4,opt,name=uuid,proto3" json:"uuid,omitempty"`
}

func (x *Asset3) Reset() {
	*x = Asset3{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tests_proto_asset_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Asset3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Asset3) ProtoMessage() {}

func (x *Asset3) ProtoReflect() protoreflect.Message {
	mi := &file_tests_proto_asset_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Asset3.ProtoReflect.Descriptor instead.
func (*Asset3) Descriptor() ([]byte, []int) {
	return file_tests_proto_asset_proto_rawDescGZIP(), []int{2}
}

func (x *Asset3) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Asset3) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Asset3) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type Asset4 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value int64  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	Uuid  string `protobuf:"bytes,4,opt,name=uuid,proto3" json:"uuid,omitempty"`
}

func (x *Asset4) Reset() {
	*x = Asset4{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tests_proto_asset_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Asset4) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Asset4) ProtoMessage() {}

func (x *Asset4) ProtoReflect() protoreflect.Message {
	mi := &file_tests_proto_asset_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Asset4.ProtoReflect.Descriptor instead.
func (*Asset4) Descriptor() ([]byte, []int) {
	return file_tests_proto_asset_proto_rawDescGZIP(), []int{3}
}

func (x *Asset4) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Asset4) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

var File_tests_proto_asset_proto protoreflect.FileDescriptor

var file_tests_proto_asset_proto_rawDesc = []byte{
	0x0a, 0x17, 0x74, 0x65, 0x73, 0x74, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x73,
	0x73, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x74, 0x65, 0x73, 0x74, 0x1a,
	0x17, 0x73, 0x61, 0x6e, 0x69, 0x74, 0x69, 0x7a, 0x65, 0x2f, 0x73, 0x61, 0x6e, 0x69, 0x74, 0x69,
	0x7a, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x66, 0x0a, 0x06, 0x41, 0x73, 0x73, 0x65,
	0x74, 0x31, 0x12, 0x18, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x42, 0x04, 0xa8, 0x88, 0x01, 0x01, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x12, 0x18, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x42, 0x04, 0xa8, 0x88, 0x01, 0x02, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x75, 0x75, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64,
	0x22, 0x4c, 0x0a, 0x06, 0x41, 0x73, 0x73, 0x65, 0x74, 0x32, 0x12, 0x18, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x04, 0xa8, 0x88, 0x01, 0x01, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75,
	0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x22, 0x4c,
	0x0a, 0x06, 0x41, 0x73, 0x73, 0x65, 0x74, 0x33, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x18,
	0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x42, 0x04, 0xa8, 0x88,
	0x01, 0x02, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x22, 0x32, 0x0a, 0x06,
	0x41, 0x73, 0x73, 0x65, 0x74, 0x34, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x75, 0x75, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64,
	0x42, 0x06, 0x5a, 0x04, 0x74, 0x65, 0x73, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tests_proto_asset_proto_rawDescOnce sync.Once
	file_tests_proto_asset_proto_rawDescData = file_tests_proto_asset_proto_rawDesc
)

func file_tests_proto_asset_proto_rawDescGZIP() []byte {
	file_tests_proto_asset_proto_rawDescOnce.Do(func() {
		file_tests_proto_asset_proto_rawDescData = protoimpl.X.CompressGZIP(file_tests_proto_asset_proto_rawDescData)
	})
	return file_tests_proto_asset_proto_rawDescData
}

var file_tests_proto_asset_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_tests_proto_asset_proto_goTypes = []interface{}{
	(*Asset1)(nil), // 0: test.Asset1
	(*Asset2)(nil), // 1: test.Asset2
	(*Asset3)(nil), // 2: test.Asset3
	(*Asset4)(nil), // 3: test.Asset4
}
var file_tests_proto_asset_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tests_proto_asset_proto_init() }
func file_tests_proto_asset_proto_init() {
	if File_tests_proto_asset_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tests_proto_asset_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Asset1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tests_proto_asset_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Asset2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tests_proto_asset_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Asset3); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tests_proto_asset_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Asset4); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tests_proto_asset_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tests_proto_asset_proto_goTypes,
		DependencyIndexes: file_tests_proto_asset_proto_depIdxs,
		MessageInfos:      file_tests_proto_asset_proto_msgTypes,
	}.Build()
	File_tests_proto_asset_proto = out.File
	file_tests_proto_asset_proto_rawDesc = nil
	file_tests_proto_asset_proto_goTypes = nil
	file_tests_proto_asset_proto_depIdxs = nil
}
