// Copyright 2021-2022 Intrinsec. All rights reserved.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: sanitize.proto

package sanitize

import (
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Sanitization int32

const (
	Sanitization_NONE Sanitization = 0
	Sanitization_TEXT Sanitization = 1
	Sanitization_HTML Sanitization = 2
)

// Enum value maps for Sanitization.
var (
	Sanitization_name = map[int32]string{
		0: "NONE",
		1: "TEXT",
		2: "HTML",
	}
	Sanitization_value = map[string]int32{
		"NONE": 0,
		"TEXT": 1,
		"HTML": 2,
	}
)

func (x Sanitization) Enum() *Sanitization {
	p := new(Sanitization)
	*p = x
	return p
}

func (x Sanitization) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Sanitization) Descriptor() protoreflect.EnumDescriptor {
	return file_sanitize_proto_enumTypes[0].Descriptor()
}

func (Sanitization) Type() protoreflect.EnumType {
	return &file_sanitize_proto_enumTypes[0]
}

func (x Sanitization) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Sanitization.Descriptor instead.
func (Sanitization) EnumDescriptor() ([]byte, []int) {
	return file_sanitize_proto_rawDescGZIP(), []int{0}
}

type FieldRules struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          Sanitization           `protobuf:"varint,1,opt,name=kind,proto3,enum=sanitize.Sanitization" json:"kind,omitempty"`
	Trim          *bool                  `protobuf:"varint,2,opt,name=trim,proto3,oneof" json:"trim,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldRules) Reset() {
	*x = FieldRules{}
	mi := &file_sanitize_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldRules) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldRules) ProtoMessage() {}

func (x *FieldRules) ProtoReflect() protoreflect.Message {
	mi := &file_sanitize_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldRules.ProtoReflect.Descriptor instead.
func (*FieldRules) Descriptor() ([]byte, []int) {
	return file_sanitize_proto_rawDescGZIP(), []int{0}
}

func (x *FieldRules) GetKind() Sanitization {
	if x != nil {
		return x.Kind
	}
	return Sanitization_NONE
}

func (x *FieldRules) GetTrim() bool {
	if x != nil && x.Trim != nil {
		return *x.Trim
	}
	return false
}

var file_sanitize_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptor.FileOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         1102,
		Name:          "sanitize.disable_file",
		Tag:           "varint,1102,opt,name=disable_file",
		Filename:      "sanitize.proto",
	},
	{
		ExtendedType:  (*descriptor.MessageOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         1102,
		Name:          "sanitize.disable_message",
		Tag:           "varint,1102,opt,name=disable_message",
		Filename:      "sanitize.proto",
	},
	{
		ExtendedType:  (*descriptor.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         1102,
		Name:          "sanitize.disable_field",
		Tag:           "varint,1102,opt,name=disable_field",
		Filename:      "sanitize.proto",
	},
	{
		ExtendedType:  (*descriptor.FieldOptions)(nil),
		ExtensionType: (*FieldRules)(nil),
		Field:         1103,
		Name:          "sanitize.rules",
		Tag:           "bytes,1103,opt,name=rules",
		Filename:      "sanitize.proto",
	},
}

// Extension fields to descriptor.FileOptions.
var (
	// optional bool disable_file = 1102;
	E_DisableFile = &file_sanitize_proto_extTypes[0]
)

// Extension fields to descriptor.MessageOptions.
var (
	// optional bool disable_message = 1102;
	E_DisableMessage = &file_sanitize_proto_extTypes[1]
)

// Extension fields to descriptor.FieldOptions.
var (
	// optional bool disable_field = 1102;
	E_DisableField = &file_sanitize_proto_extTypes[2]
	// optional sanitize.FieldRules rules = 1103;
	E_Rules = &file_sanitize_proto_extTypes[3]
)

var File_sanitize_proto protoreflect.FileDescriptor

const file_sanitize_proto_rawDesc = "" +
	"\n" +
	"\x0esanitize.proto\x12\bsanitize\x1a google/protobuf/descriptor.proto\"Z\n" +
	"\n" +
	"FieldRules\x12*\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x16.sanitize.SanitizationR\x04kind\x12\x17\n" +
	"\x04trim\x18\x02 \x01(\bH\x00R\x04trim\x88\x01\x01B\a\n" +
	"\x05_trim*,\n" +
	"\fSanitization\x12\b\n" +
	"\x04NONE\x10\x00\x12\b\n" +
	"\x04TEXT\x10\x01\x12\b\n" +
	"\x04HTML\x10\x02:@\n" +
	"\fdisable_file\x12\x1c.google.protobuf.FileOptions\x18\xce\b \x01(\bR\vdisableFile:I\n" +
	"\x0fdisable_message\x12\x1f.google.protobuf.MessageOptions\x18\xce\b \x01(\bR\x0edisableMessage:C\n" +
	"\rdisable_field\x12\x1d.google.protobuf.FieldOptions\x18\xce\b \x01(\bR\fdisableField:J\n" +
	"\x05rules\x12\x1d.google.protobuf.FieldOptions\x18\xcf\b \x01(\v2\x14.sanitize.FieldRulesR\x05rulesB3Z1github.com/intrinsec/protoc-gen-sanitize/sanitizeb\x06proto3"

var (
	file_sanitize_proto_rawDescOnce sync.Once
	file_sanitize_proto_rawDescData []byte
)

func file_sanitize_proto_rawDescGZIP() []byte {
	file_sanitize_proto_rawDescOnce.Do(func() {
		file_sanitize_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sanitize_proto_rawDesc), len(file_sanitize_proto_rawDesc)))
	})
	return file_sanitize_proto_rawDescData
}

var file_sanitize_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_sanitize_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_sanitize_proto_goTypes = []any{
	(Sanitization)(0),                 // 0: sanitize.Sanitization
	(*FieldRules)(nil),                // 1: sanitize.FieldRules
	(*descriptor.FileOptions)(nil),    // 2: google.protobuf.FileOptions
	(*descriptor.MessageOptions)(nil), // 3: google.protobuf.MessageOptions
	(*descriptor.FieldOptions)(nil),   // 4: google.protobuf.FieldOptions
}
var file_sanitize_proto_depIdxs = []int32{
	0, // 0: sanitize.FieldRules.kind:type_name -> sanitize.Sanitization
	2, // 1: sanitize.disable_file:extendee -> google.protobuf.FileOptions
	3, // 2: sanitize.disable_message:extendee -> google.protobuf.MessageOptions
	4, // 3: sanitize.disable_field:extendee -> google.protobuf.FieldOptions
	4, // 4: sanitize.rules:extendee -> google.protobuf.FieldOptions
	1, // 5: sanitize.rules:type_name -> sanitize.FieldRules
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	5, // [5:6] is the sub-list for extension type_name
	1, // [1:5] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_sanitize_proto_init() }
func file_sanitize_proto_init() {
	if File_sanitize_proto != nil {
		return
	}
	file_sanitize_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sanitize_proto_rawDesc), len(file_sanitize_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 4,
			NumServices:   0,
		},
		GoTypes:           file_sanitize_proto_goTypes,
		DependencyIndexes: file_sanitize_proto_depIdxs,
		EnumInfos:         file_sanitize_proto_enumTypes,
		MessageInfos:      file_sanitize_proto_msgTypes,
		ExtensionInfos:    file_sanitize_proto_extTypes,
	}.Build()
	File_sanitize_proto = out.File
	file_sanitize_proto_goTypes = nil
	file_sanitize_proto_depIdxs = nil
}
